### ISSUE TITLE
[Bug] IndexError: Replacement index 1 out of range for positional args tuple when running `binning-eukaryotic.py`

### ISSUE THREAD

**Issue by jolespin** [jolespin/veba#11]
**Describe the bug:**
MetaEuk runs to completion but the `compile_metaeuk_identifiers.py` script throws an error when there are duplicate gene identifiers.

**Versions**

v1.0.3

**Command used to produce error:**
Steps to reproduce the behavior

```
(VEBA-binning-eukaryotic_env) compile_metaeuk_identifiers.py --cds veba_output/binning/eukaryotic/G00009_30-PE-D703D505-1_S109/intermediate/2__metaeuk/metaeuk.codon.fas --protein veba_output/binning/eukaryotic/G00009_30-PE-D703D505-1_S109/intermediate/2__metaeuk/metaeuk.fas -o veba_output/binning/eukaryotic/G00009_30-PE-D703D505-1_S109/intermediate/2__metaeuk -b gene_models
Parsing MetaEuk headers: 100%|███████████████████████████████████████████████████████████████████████████████| 4124/4124 [00:00<00:00, 143228.78 gene/s]
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-eukaryotic_env/bin/compile_metaeuk_identifiers.py", line 353, in <module>
    main()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-eukaryotic_env/bin/compile_metaeuk_identifiers.py", line 227, in main
    print("There are {} duplicate gene identifiers:{}".format((geneid_value_counts > 1).sum()), file=sys.stderr)
IndexError: Replacement index 1 out of range for positional args tuple
```

**Comment by jolespin** [comment]
Fixed here: [c248527da9edef5ba2ebee348d707d8ece29fbee](https://github.com/jolespin/veba/commit/c248527da9edef5ba2ebee348d707d8ece29fbee)
