### ISSUE TITLE
[Bug] binning-prok fails with scaffolds_to_bins.tsv file missing

### ISSUE THREAD

**Issue by hyphaltip** [jolespin/veba#4]
```
Validating the following output files:
Traceback (most recent call last):
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2384, in <module>
    main()
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2380, in main
    pipeline.execute(restart_from_checkpoint=opts.restart_from_checkpoint)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 780, in execute
    validate_file_existence(output_filepaths, prologue="\nValidating the following output files:", f_verbose=self.f_verbose)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 78, in validate_file_existence
    assert os.path.exists(path), "The following path does not exist: {}".format(path)
AssertionError: The following path does not exist: veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv
```

if I copy the file scaffolds_to_bins.tsv to the folder I then get
```
Validating the following output files:
[=] File exists (105063 bytes): veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv
Traceback (most recent call last):
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2394, in <module>
    main()
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2390, in main
    pipeline.execute(restart_from_checkpoint=opts.restart_from_checkpoint)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 780, in execute
    validate_file_existence(output_filepaths, prologue="\nValidating the following output files:", f_verbose=self.f_verbose)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 78, in validate_file_existence
    assert os.path.exists(path), "The following path does not exist: {}".format(path)
AssertionError: The following path does not exist: veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/binned.list
```

**Comment by hyphaltip** [comment]
I thought i was adding to the pipeline the correct location for copying files and generating the binned.list changes but it doesn't seem to be working.
If I then generate the binned.list manually
```
Validating the following output files:
[=] File exists (105063 bytes): veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv
[=] File exists (56732 bytes): veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/binned.list
Traceback (most recent call last):
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2394, in <module>
    main()
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/binning-prokaryotic.py", line 2390, in main
    pipeline.execute(restart_from_checkpoint=opts.restart_from_checkpoint)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 780, in execute
    validate_file_existence(output_filepaths, prologue="\nValidating the following output files:", f_verbose=self.f_verbose)
  File "/opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/lib/python3.8/site-packages/genopype/genopype.py", line 78, in validate_file_existence
    assert os.path.exists(path), "The following path does not exist: {}".format(path)
AssertionError: The following path does not exist: veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/unbinned.fasta
``` 

so something isn't running in the pipeline even though all those steps are correct from what I can see in the cmd
```
Input: ['veba_output/binning/prokaryotic/sim_1/intermediate/*__checkm/filtered/scaffolds_to_bins.tsv', 'veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.gff', 'veba_output/bi
nning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.ffn', 'veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.faa']
Output: ['veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv', 'veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/binned.list', 'veba_outpu
t/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/unbinned.fasta', 'veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/unbinned.list', 'veba_output/binning/prokaryotic/sim
_1/intermediate/63__cpr_adjustment/genomes', 'veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/bins.list', 'veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/c
heckm_output.filtered.tsv', 'veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output.filtered.tsv']

Command:
export GTDBTK_DATA_PATH=/srv/projects/db/VEBA/1.0.0/Classify/GTDBTk && mkdir -p veba_output/binning/prokaryotic/sim_1/tmp/genomes && mkdir -p veba_output/binning/prokaryotic/sim_1/tmp/proteins && mkdi
r -p veba_output/binning/prokaryotic/sim_1/tmp/proteins/cpr_bacteria && mkdir -p veba_output/binning/prokaryotic/sim_1/tmp/proteins/non-cpr_prokaryotes && cat veba_output/binning/prokaryotic/sim_1/int
ermediate/*__checkm/filtered/scaffolds_to_bins.tsv > veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffol
ds_to_bins.tsv && cut -f1 veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv > veba_outpu
t/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/binned.list && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs
/VEBA-binning-prokaryotic_env/bin/scripts/partition_gene_models.py -i veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_a
djustment/scaffolds_to_bins.tsv -f veba_output/assembly/sim_1/output/scaffolds.fasta -g veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.gff -d veba_output/binning/prokaryoti
c/sim_1/intermediate/2__prodigal/gene_models.ffn -a veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.faa -o veba_output/binning/prokaryotic/sim_1/tmp/genomes && mkdir -p veba
_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output && /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/gtdbtk classify_wf --genome_dir veb
a_output/binning/prokaryotic/sim_1/tmp/genomes --pplacer_cpus 1 --out_dir veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output -x fa --cpus 16 --tmpdir veba_output/binni
ng/prokaryotic/sim_1/tmp  && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/scripts/concatenate_dataframes.py --axis 0 --allow_empty_or_missing_files veba_out
put/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/classify/gtdbtk.ar122.summary.tsv veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/classi
fy/gtdbtk.bac120.summary.tsv > veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/gtdbtk.summary.tsv && ( cat veba_output/binning/prokaryotic/sim_1/intermediate/63__cp
r_adjustment/gtdbtk_output/classify/gtdbtk.bac120.summary.tsv | grep 'Patescibacteria' | cut -f1 > veba_output/binning/prokaryotic/sim_1/tmp/genomes/cpr_bacteria.list && cat veba_output/binning/prokar
yotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/classify/gtdbtk.bac120.summary.tsv | grep -v 'Patescibacteria' | cut -f1 | tail -n +2 > veba_output/binning/prokaryotic/sim_1/tmp/genomes/non-
cpr_bacteria.list ) 2> /dev/null || ( echo 'No bacterial genomes' && > veba_output/binning/prokaryotic/sim_1/tmp/genomes/cpr_bacteria.list && > veba_output/binning/prokaryotic/sim_1/tmp/genomes/non-cp
r_bacteria.list ) && ( cat veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/classify/gtdbtk.ar122.summary.tsv | cut -f1 | tail -n +2 > veba_output/binning/prokaryoti
c/sim_1/tmp/genomes/archaea.list ) 2> /dev/null || ( echo 'No archael genomes' && > veba_output/binning/prokaryotic/sim_1/tmp/genomes/archaea.list ) && for ID in $(cat veba_output/binning/prokaryotic/
sim_1/tmp/genomes/non-cpr_bacteria.list veba_output/binning/prokaryotic/sim_1/tmp/genomes/archaea.list); do cp veba_output/binning/prokaryotic/sim_1/tmp/genomes/${ID}.faa veba_output/binning/prokaryot
ic/sim_1/tmp/proteins/non-cpr_prokaryotes; done && for ID in $(cat veba_output/binning/prokaryotic/sim_1/tmp/genomes/cpr_bacteria.list); do cp veba_output/binning/prokaryotic/sim_1/tmp/genomes/${ID}.f
aa veba_output/binning/prokaryotic/sim_1/tmp/proteins/cpr_bacteria; done && mkdir -p veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output && mkdir -p veba_output/binning
/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/non-cpr_prokaryotes && mkdir -p veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacteria && ( (
 /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/checkm lineage_wf -r -g --tab_table -f veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_o
utput/non-cpr_prokaryotes/output.tsv --pplacer_threads 1 -t 16 -x faa --tmpdir veba_output/binning/prokaryotic/sim_1/tmp veba_output/binning/prokaryotic/sim_1/tmp/proteins/non-cpr_prokaryotes veba_out
put/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/non-cpr_prokaryotes && rm -rf veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/non-cpr_pr
okaryotes/bins veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/non-cpr_prokaryotes/storage ) || > veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustm
ent/checkm_output/non-cpr_prokaryotes/output.tsv && ( /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/checkm analyze -g -x faa -t 16 --tmpdir veba_output/binning/prok
aryotic/sim_1/tmp /srv/projects/db/VEBA/1.0.0/MarkerSets/CPR_43.hmm veba_output/binning/prokaryotic/sim_1/tmp/proteins/cpr_bacteria veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustmen
t/checkm_output/cpr_bacteria && /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/checkm qa --tab_table -f veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_ad
justment/checkm_output/cpr_bacteria/output.tsv /srv/projects/db/VEBA/1.0.0/MarkerSets/CPR_43.hmm veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacteria && rm
-rf veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacteria/bins veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacter
ia/storage ) || > veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacteria/output.tsv ) && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-
prokaryotic_env/bin/scripts/concatenate_dataframes.py --axis 0 --allow_empty_or_missing_files veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/non-cpr_prokaryotes/ou
tput.tsv veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_output/cpr_bacteria/output.tsv > veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/checkm_outp
ut/output.concatenated.tsv && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/scripts/filter_checkm_results.py -i veba_output/binning/prokaryotic/sim_1/interme
diate/63__cpr_adjustment/checkm_output/output.concatenated.tsv -b veba_output/binning/prokaryotic/sim_1/tmp/genomes -o veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment -f veba_out
put/assembly/sim_1/output/scaffolds.fasta -m 1500 --unbinned --completeness 50.0 --contamination 10.0  -x fa && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin
/scripts/partition_gene_models.py -i veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/scaffolds_to_bins.tsv -g veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_
models.gff -d veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.ffn -a veba_output/binning/prokaryotic/sim_1/intermediate/2__prodigal/gene_models.faa -o veba_output/binning/pr
okaryotic/sim_1/intermediate/63__cpr_adjustment/genomes && python /opt/linux/rocky/8.x/x86_64/pkgs/veba/1.0.0/envs/VEBA-binning-prokaryotic_env/bin/scripts/subset_table.py -t veba_output/binning/proka
ryotic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output/gtdbtk.summary.tsv -i veba_output/binning/prokaryotic/sim_1/intermediate/63__cpr_adjustment/bins.list --axis 0 > veba_output/binning/prokaryo
tic/sim_1/intermediate/63__cpr_adjustment/gtdbtk_output.filtered.tsv
```

**Comment by jolespin** [comment]
Ok yea this can be a tricky error but I think I know what's going on as I've dealt with this before. 

Can you take a look at #13, #15 and #20 here: https://github.com/jolespin/veba/blob/main/FAQ.md

If not, can you send me some of the log files so I can help you diagnose this.

**Comment by hyphaltip** [comment]
sure -- we are running on simulated data comparing our current pipelines first. possible we don't have a good coverage to give back expected MAGs - we can try some richer dataset too.

I guess then a check that there are only empty MAGs rather than a python crash with missing file error would be helpful or just a message referencing the FAQ I guess could help too. 
[binning_prok_errors_restart.log](https://github.com/jolespin/veba/files/9834758/binning_prok_errors_restart.log)

**Comment by hyphaltip** [comment]
doesn't look like there is a pending checkM2 bioconda recipe - I can see about getting that in too.

**Comment by chtsai0105** [comment]
Hi, I followed the #15 in the FAQ and get the information as below. There are several bins that are not labeled as K__Bacteria and also with high completeness and low contamination.

```
veba_output/binning/prokaryotic/sim_1/intermediate/8__checkm/filtered/checkm_output.filtered.tsv
Bin Id  Marker lineage  # genomes       # markers       # marker sets   0       1       2       3       4       5+      Completeness    Contamination   Strain heterogeneity
sim_1__CONCOCT__P.1__3  o__Actinomycetales (UID1812)    229     457     227     3       453     1       0       0       0       99.45   0.44    0.0
sim_1__MAXBIN2-107__P.1__bin.001_sub    k__Bacteria (UID3060)   138     338     246     0       336     1       1       0       0       100.0   0.95    0.0
sim_1__MAXBIN2-40__P.1__bin.005_sub     f__Pasteurellaceae (UID4932)    83      767     440     6       759     2       0       0       0       99.16   0.19    0.0
sim_1__MAXBIN2-40__P.1__bin.006_sub     c__Gammaproteobacteria (UID4442)        899     312     185     6       304     2       0       0       0       98.93   1.08    0.0
sim_1__METABAT2__P.1__bin.12    o__Rhizobiales (UID3451)        237     514     245     2       512     0       0       0       0       99.46   0.0     0.0
sim_1__METABAT2__P.1__bin.4_sub c__Gammaproteobacteria (UID4274)        112     581     290     4       574     3       0       0       0       99.51   0.8     0.0
sim_1__METABAT2__P.1__bin.6     o__Pseudomonadales (UID4488)    185     813     308     200     600     12      1       0       0       75.9    2.01    6.67
sim_1__METABAT2__P.1__bin.7     k__Bacteria (UID209)    5443    102     57      66      36      0       0       0       0       24.57   0.0     0.0
```

**Comment by jolespin** [comment]
Ok yea there should be a bunch that go through.  How much memory are you allocating? The version of GTDB-Tk is v1.x and it uses quite a bit (next version will use GTDB-Tk v2).  Can you try allocating 243G and try again with --restart_from_checkpoint 63 (assuming you ran 10 iterations)? If that doesn't work, would you mind sending me your `scaffolds.fasta` and `mapped.sorted.bam` files?  Apologies for these errors and the inconvenience, I've run it several times on different datasets without any errors so I thought I caught everything.  I'll make this a top priority.

**Comment by jolespin** [comment]
@hyphaltip would you mind sending me your scaffolds.fasta and mapped.sorted.bam file along with the commands you ran? I'll try it out tomorrow morning after some coffee.  Your suggestion for the error message is great, I'll try to incorporate that in an upcoming version as well.  I'll make custom error messages for specific steps in the pipeline.  Will need to make some minor mods to GenoPype.

**Comment by jolespin** [comment]
@hyphaltip just following up on our previous conversation: 
* Have you tried allocating 243G of memory for the last step?; 
* If you don't have time to try the above, would you mind sharing your `scaffolds.fasta` and `mapped.sorted.bam` files (I'll run this today)?  This will be helpful on my end to have access to a simulated dataset with edge cases.

I have some downtime between projects which will change in the next day or so.

**Comment by hyphaltip** [comment]
Can try soon. Busy week. That's a lot of ram for binning / classify but will give it a go. 

Checkm2 doesn't have official release so it makes it harder to condaize but am part of way thru

**Comment by jolespin** [comment]
@hyphaltip Agreed, it's a lot of RAM but this is just for classification step (not binning) and this amount may be required (maybe less) for larger datasets when using GTDB-Tk v1(noted #15 of the [FAQ](https://github.com/jolespin/veba/blob/main/FAQ.md)).  

Note, I'm updating to GTDB-Tk v2 w/ the appropriate database (this uses much less RAM) in the next patch.  Unfortunately, GTDB-Tk v2 wasn't available when I was initially creating this.

**Comment by asaldivar93** [comment]
Hi @jolespin, 
I was unsure if I should open a new issue about this. Running the pipeline in three mock datasets we use in our lab throws the same error. However, when debugging I found that the intermediate DAStool directories were totally empty. When we ran the DAStool/CheckM commands manually, we found over 18 High-quality MAGs for each dataset. In summary, when running the pipeline the DAStool directories are empty, but inputting the commands manually does find high-quality MAGs.

Pd: found your work on Reddit. It has been both useful and highly educational, Thank you.

**Comment by jolespin** [comment]
@asaldivar93 Can you send me your scaffolds.fasta and mapped.sorted.bam files? I'll need to run it manually to find the source of the error. I'm still working on more productive error messages.

**Comment by jolespin** [comment]
I've updated GTDB-Tk v1.x to v2.x which should take care of the memory issues.  I ran 

Here's the release: 
https://github.com/jolespin/veba/releases/tag/v1.0.2a 

You can track all of the changes made through the release. 

If you don't want to do a full reinstall then check out the patch guide: 
https://github.com/jolespin/veba/blob/main/install/PATCHES.md

If the issue is still around, then I'll reopen.  If we need to reopen, please provide the `scaffolds.fasta` and `mapped.sorted.bam` files or else I won't be able to be much help.  Adjusting the error messages isn't trivial but it's something I'm working on. 

I just tested it on the following assembly, here's the stats: 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/9061708/198167646-c7042025-b584-40c9-bb50-df9650db79ce.png">

**Comment by jolespin** [comment]
[v1.0.3](https://github.com/jolespin/veba/releases/tag/v1.0.3) has better error messages for the penultimate step of `binning-prokaryotic.py`.

**Comment by jolespin** [comment]
@hyphaltip just wanted to give you a heads up that I will be updating VEBA to include CheckM2 in the next version.  This should help out with the error messages involved with this issue.  I'm also adding MMSEQS2 as an option for clustering proteins which will decrease the resources/compute time substantially for the `cluster.py` module.  Once I have tested the update, I will post the link here.

**Comment by jolespin** [comment]
@hyphaltip I've updated VEBA to use CheckM2 to get around the resource intensive GTDB-Tk requirements in the binning.  It is MUCH faster and easier to use now.  I've also included a major update to the clustering module while adding a biosynthetic module as well.  Here's a full list of the changes: https://github.com/jolespin/veba/blob/main/DEVELOPMENT.md#release-v111
