### ISSUE TITLE
Issue: Broken pipe error in kofamscan step

### ISSUE THREAD

**Issue by nicolazarte** [jolespin/veba#46]
Dear Josh,

I hope this message finds you well. I am currently using VEBA 1.3.0 on a server, and I am encountering an issue during the annotation step, specifically with the kofamscan tool.

```
> 
> =============
> . kofamscan .
> =============
> Input: ['veba_output/misc/all_genomes.all_proteins.lt100k.faa', '/home/ec2-user/veba_efs/database/Annotate/KOFAM/profiles', '/home/ec2-user/veba_efs/database/Annotate/KOFAM/ko_list']
> Output: ['veba_output/annotation/intermediate/8__kofamscan/output.tsv.gz']
> 
> Command:
> ( mkdir -p veba_output/annotation/tmp/kofamscan && /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/exec_annotation --cpu 36 -f detail-tsv -p /home/ec2-user/veba_efs/database/Annotate/KOFAM/profiles -k /home/ec2-user/veba_efs/database/Annotate/KOFAM/ko_list --tmp-dir veba_output/annotation/tmp/kofamscan veba_output/misc/all_genomes.all_proteins.lt100k.faa | grep "*" > veba_output/annotation/intermediate/8__kofamscan/output.tsv ) && pigz -f -p 36 veba_output/annotation/intermediate/8__kofamscan/output.tsv 
> 
> Validating the following input files:
> [=] File exists (905 MB): veba_output/misc/all_genomes.all_proteins.lt100k.faa
> [=] Directory exists (6832 MB): /home/ec2-user/veba_efs/database/Annotate/KOFAM/profiles
> [=] File exists (2 MB): /home/ec2-user/veba_efs/database/Annotate/KOFAM/ko_list
> 
> Running. .. ... .....
> Check log files to diagnose error:
> cat veba_output/annotation/log/8__kofamscan.*
> 
> cat veba_output/annotation/log/8__kofamscan.*
> /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/parallel.rb:28:in `write': Broken pipe (Errno::EPIPE)
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/parallel.rb:28:in `puts'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/parallel.rb:28:in `block in exec'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/lib/ruby/2.7.0/open3.rb:219:in `popen_run'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/lib/ruby/2.7.0/open3.rb:101:in `popen3'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/parallel.rb:27:in `exec'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/executor.rb:107:in `run_hmmsearch'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/executor.rb:35:in `execute'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/executor.rb:8:in `execute'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/lib/kofam_scan/cli.rb:21:in `run'
> 	from /home/ec2-user/veba_efs/mambaforge/envs/VEBA-annotate_env/bin/exec_annotation:7:in `<main>'
> 1
> 
> 
```

I have attempted to resolve the issue by referring to the GitHub repository ([https://github.com/takaram/kofam_scan/issues/7](https://github.com/takaram/kofam_scan/issues/7)), but I couldn't find a solution that works for my case.

I would appreciate any guidance or assistance you could provide to help resolve this issue.
Thank you for your time and support.

**Comment by nicolazarte** [comment]
I'm sorry to bother you. It seems I solved it by running the containerized Docker version. 
I'm closing the issue. 
Thanks again.

**Comment by jolespin** [comment]
Let me know if you encounter any other problems. 

Did you run it via Docker or Singularity?

**Comment by nicolazarte** [comment]
I fixed it by running via Docker. In my previous attempt I wasn't using any container, just the installed version.
